/**
 * Demo seed data — 28 employees for AstraPlanner demo mode.
 * Shapes match tRPC router responses exactly (workforce.ts).
 */

import {
  DEMO_SITE_AMS, DEMO_SITE_RTM,
  DEPT_INBOUND_AMS, DEPT_OUTBOUND_AMS, DEPT_INBOUND_RTM, DEPT_VAS_AMS, DEPT_SHIPPING_AMS,
  ROLE_ORDERPICKER, ROLE_TEAMLEIDER, ROLE_LOG_MED, ROLE_INPAKKER, ROLE_VERZENDMEDEWERKER,
  PROC_ORDER_PICKING, PROC_INBOUND, PROC_PACKING, PROC_VAS, PROC_SHIPPING, PROC_RETURNS,
} from './demo-seed-processes'

// ── AMS — Teamleiders (4) ─────────────────────────────────────────────────────

export const demoEmployees = [
  {
    id: 'demo-emp-0000-0000-0000-000000000001',
    employee_number: 'AMS-001',
    first_name: 'Sanne',
    last_name: 'Bakker',
    email: 'sanne.bakker@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_TEAMLEIDER,
    hourly_rate: 18.00,
    status: 'active',
    is_multi_site_eligible: true,
    skill_count: 3,
    skills: [
      { id: 'demo-skl-100', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking',     proficiency_level: 5, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-101', process_id: PROC_PACKING,       process_name: 'Packing',           proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-102', process_id: PROC_SHIPPING,      process_name: 'Shipping',          proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000002',
    employee_number: 'AMS-002',
    first_name: 'Pieter',
    last_name: 'de Jong',
    email: 'pieter.dejong@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_INBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_TEAMLEIDER,
    hourly_rate: 17.50,
    status: 'active',
    is_multi_site_eligible: true,
    skill_count: 3,
    skills: [
      { id: 'demo-skl-103', process_id: PROC_INBOUND,  process_name: 'Inbound Receiving',  proficiency_level: 5, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-104', process_id: PROC_RETURNS,  process_name: 'Returns Processing', proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-105', process_id: PROC_VAS,      process_name: 'VAS',                proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000003',
    employee_number: 'AMS-003',
    first_name: 'Youssef',
    last_name: 'el Amrani',
    email: 'youssef.elamrani@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_VAS_AMS,
    crew_id: null,
    job_role_id: ROLE_TEAMLEIDER,
    hourly_rate: 18.50,
    status: 'active',
    is_multi_site_eligible: true,
    skill_count: 3,
    skills: [
      { id: 'demo-skl-106', process_id: PROC_VAS,      process_name: 'VAS',      proficiency_level: 5, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-107', process_id: PROC_SHIPPING, process_name: 'Shipping', proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-108', process_id: PROC_PACKING,  process_name: 'Packing',  proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000004',
    employee_number: 'AMS-004',
    first_name: 'Lisa',
    last_name: 'van Dijk',
    email: 'lisa.vandijk@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_TEAMLEIDER,
    hourly_rate: 17.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 3,
    skills: [
      { id: 'demo-skl-109', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking', proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-110', process_id: PROC_PACKING,       process_name: 'Packing',       proficiency_level: 5, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-111', process_id: PROC_VAS,           process_name: 'VAS',           proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },

  // ── AMS — Orderpickers (6) ────────────────────────────────────────────────────

  {
    id: 'demo-emp-0000-0000-0000-000000000005',
    employee_number: 'AMS-005',
    first_name: 'Lars',
    last_name: 'van den Berg',
    email: 'lars.vandenberg@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_ORDERPICKER,
    hourly_rate: 14.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-112', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking',    proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-113', process_id: PROC_INBOUND,       process_name: 'Inbound Receiving', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000006',
    employee_number: 'AMS-006',
    first_name: 'Femke',
    last_name: 'de Vries',
    email: 'femke.devries@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_ORDERPICKER,
    hourly_rate: 14.00,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-114', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000007',
    employee_number: 'AMS-007',
    first_name: 'Daan',
    last_name: 'Meijer',
    email: 'daan.meijer@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_ORDERPICKER,
    hourly_rate: 14.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-115', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking', proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-116', process_id: PROC_PACKING,       process_name: 'Packing',       proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000008',
    employee_number: 'AMS-008',
    first_name: 'Eva',
    last_name: 'Koopman',
    email: 'eva.koopman@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_ORDERPICKER,
    hourly_rate: 15.00,
    status: 'active',
    is_multi_site_eligible: true,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-117', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking',    proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-118', process_id: PROC_INBOUND,       process_name: 'Inbound Receiving', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000009',
    employee_number: 'AMS-009',
    first_name: 'Mark',
    last_name: 'Willems',
    email: 'mark.willems@astrademo.nl',
    contract_type: 'part_time',
    weekly_hours_contracted: 32,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_ORDERPICKER,
    hourly_rate: 14.00,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-119', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-120', process_id: PROC_PACKING,       process_name: 'Packing',       proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000010',
    employee_number: 'AMS-010',
    first_name: 'Sophie',
    last_name: 'Mulder',
    email: 'sophie.mulder@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_ORDERPICKER,
    hourly_rate: 14.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-121', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-122', process_id: PROC_VAS,           process_name: 'VAS',           proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },

  // ── AMS — Logistiek Medewerkers (4) ──────────────────────────────────────────

  {
    id: 'demo-emp-0000-0000-0000-000000000011',
    employee_number: 'AMS-011',
    first_name: 'Joost',
    last_name: 'Hendriks',
    email: 'joost.hendriks@astrademo.nl',
    contract_type: 'part_time',
    weekly_hours_contracted: 24,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_INBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-123', process_id: PROC_INBOUND, process_name: 'Inbound Receiving', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000012',
    employee_number: 'AMS-012',
    first_name: 'Bram',
    last_name: 'Lammers',
    email: 'bram.lammers@astrademo.nl',
    contract_type: 'part_time',
    weekly_hours_contracted: 32,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_INBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-124', process_id: PROC_INBOUND,  process_name: 'Inbound Receiving',  proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-125', process_id: PROC_RETURNS,  process_name: 'Returns Processing', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000013',
    employee_number: 'AMS-013',
    first_name: 'Nadia',
    last_name: 'Boualem',
    email: 'nadia.boualem@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_INBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 14.00,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-126', process_id: PROC_INBOUND,  process_name: 'Inbound Receiving',  proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-127', process_id: PROC_RETURNS,  process_name: 'Returns Processing', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000014',
    employee_number: 'AMS-014',
    first_name: 'Roy',
    last_name: 'Groen',
    email: 'roy.groen@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_INBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-128', process_id: PROC_INBOUND, process_name: 'Inbound Receiving', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-129', process_id: PROC_VAS,     process_name: 'VAS',               proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },

  // ── AMS — Inpakkers (3) ───────────────────────────────────────────────────────

  {
    id: 'demo-emp-0000-0000-0000-000000000015',
    employee_number: 'AMS-015',
    first_name: 'Anouk',
    last_name: 'Peters',
    email: 'anouk.peters@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_INPAKKER,
    hourly_rate: 14.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-130', process_id: PROC_PACKING, process_name: 'Packing', proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-131', process_id: PROC_VAS,     process_name: 'VAS',     proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000016',
    employee_number: 'AMS-016',
    first_name: 'Tim',
    last_name: 'Jansen',
    email: 'tim.jansen@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_INPAKKER,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-132', process_id: PROC_PACKING, process_name: 'Packing', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000017',
    employee_number: 'AMS-017',
    first_name: 'Roos',
    last_name: 'Vermeer',
    email: 'roos.vermeer@astrademo.nl',
    contract_type: 'part_time',
    weekly_hours_contracted: 24,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_OUTBOUND_AMS,
    crew_id: null,
    job_role_id: ROLE_INPAKKER,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-133', process_id: PROC_PACKING,  process_name: 'Packing',           proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-134', process_id: PROC_RETURNS,  process_name: 'Returns Processing', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },

  // ── AMS — Verzendmedewerkers (3) ─────────────────────────────────────────────

  {
    id: 'demo-emp-0000-0000-0000-000000000018',
    employee_number: 'AMS-018',
    first_name: 'Carmen',
    last_name: 'de Groot',
    email: 'carmen.degroot@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_SHIPPING_AMS,
    crew_id: null,
    job_role_id: ROLE_VERZENDMEDEWERKER,
    hourly_rate: 14.00,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-135', process_id: PROC_SHIPPING, process_name: 'Shipping', proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-136', process_id: PROC_PACKING,  process_name: 'Packing',  proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000019',
    employee_number: 'AMS-019',
    first_name: 'Wouter',
    last_name: 'Dijkstra',
    email: 'wouter.dijkstra@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_SHIPPING_AMS,
    crew_id: null,
    job_role_id: ROLE_VERZENDMEDEWERKER,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-137', process_id: PROC_SHIPPING, process_name: 'Shipping', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000020',
    employee_number: 'AMS-020',
    first_name: 'Fatima',
    last_name: 'el Idrissi',
    email: 'fatima.elidrissi@astrademo.nl',
    contract_type: 'flex',
    weekly_hours_contracted: 20,
    home_site_id: DEMO_SITE_AMS,
    department_id: DEPT_SHIPPING_AMS,
    crew_id: null,
    job_role_id: ROLE_VERZENDMEDEWERKER,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-138', process_id: PROC_SHIPPING, process_name: 'Shipping', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-139', process_id: PROC_VAS,      process_name: 'VAS',      proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },

  // ── RTM — Teamleider (1) ──────────────────────────────────────────────────────

  {
    id: 'demo-emp-0000-0000-0000-000000000021',
    employee_number: 'RTM-001',
    first_name: 'Nina',
    last_name: 'Smit',
    email: 'nina.smit@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_RTM,
    department_id: DEPT_INBOUND_RTM,
    crew_id: null,
    job_role_id: ROLE_TEAMLEIDER,
    hourly_rate: 18.50,
    status: 'active',
    is_multi_site_eligible: true,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-140', process_id: PROC_INBOUND, process_name: 'Inbound Receiving', proficiency_level: 5, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },

  // ── RTM — Logistiek Medewerkers (4) ──────────────────────────────────────────

  {
    id: 'demo-emp-0000-0000-0000-000000000022',
    employee_number: 'RTM-002',
    first_name: 'Tom',
    last_name: 'Janssen',
    email: 'tom.janssen@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_RTM,
    department_id: DEPT_INBOUND_RTM,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-141', process_id: PROC_INBOUND, process_name: 'Inbound Receiving', proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000023',
    employee_number: 'RTM-003',
    first_name: 'Anouk',
    last_name: 'Visser',
    email: 'anouk.visser@astrademo.nl',
    contract_type: 'flex',
    weekly_hours_contracted: 20,
    home_site_id: DEMO_SITE_RTM,
    department_id: DEPT_INBOUND_RTM,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-142', process_id: PROC_INBOUND, process_name: 'Inbound Receiving', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000024',
    employee_number: 'RTM-004',
    first_name: 'Milan',
    last_name: 'Kuipers',
    email: 'milan.kuipers@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_RTM,
    department_id: DEPT_INBOUND_RTM,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-143', process_id: PROC_INBOUND,  process_name: 'Inbound Receiving',  proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-144', process_id: PROC_RETURNS,  process_name: 'Returns Processing', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000025',
    employee_number: 'RTM-005',
    first_name: 'Lotte',
    last_name: 'Brouwer',
    email: 'lotte.brouwer@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_RTM,
    department_id: DEPT_INBOUND_RTM,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-145', process_id: PROC_INBOUND, process_name: 'Inbound Receiving', proficiency_level: 4, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },

  // ── RTM — Orderpickers (2) ────────────────────────────────────────────────────

  {
    id: 'demo-emp-0000-0000-0000-000000000026',
    employee_number: 'RTM-006',
    first_name: 'Thijs',
    last_name: 'van Leeuwen',
    email: 'thijs.vanleeuwen@astrademo.nl',
    contract_type: 'full_time',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_RTM,
    department_id: DEPT_INBOUND_RTM,
    crew_id: null,
    job_role_id: ROLE_ORDERPICKER,
    hourly_rate: 14.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-146', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking',    proficiency_level: 3, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-147', process_id: PROC_INBOUND,       process_name: 'Inbound Receiving', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
  {
    id: 'demo-emp-0000-0000-0000-000000000027',
    employee_number: 'RTM-007',
    first_name: 'Julia',
    last_name: 'Vos',
    email: 'julia.vos@astrademo.nl',
    contract_type: 'seasonal',
    weekly_hours_contracted: 40,
    home_site_id: DEMO_SITE_RTM,
    department_id: DEPT_INBOUND_RTM,
    crew_id: null,
    job_role_id: ROLE_ORDERPICKER,
    hourly_rate: 14.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 1,
    skills: [
      { id: 'demo-skl-148', process_id: PROC_ORDER_PICKING, process_name: 'Order Picking', proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },

  // ── RTM — Flex worker (1) ─────────────────────────────────────────────────────

  {
    id: 'demo-emp-0000-0000-0000-000000000028',
    employee_number: 'RTM-008',
    first_name: 'Sem',
    last_name: 'de Wit',
    email: 'sem.dewit@astrademo.nl',
    contract_type: 'flex',
    weekly_hours_contracted: 16,
    home_site_id: DEMO_SITE_RTM,
    department_id: DEPT_INBOUND_RTM,
    crew_id: null,
    job_role_id: ROLE_LOG_MED,
    hourly_rate: 13.50,
    status: 'active',
    is_multi_site_eligible: false,
    skill_count: 2,
    skills: [
      { id: 'demo-skl-149', process_id: PROC_INBOUND,  process_name: 'Inbound Receiving',  proficiency_level: 2, certification_date: null, expiry_date: null, last_practiced_date: null },
      { id: 'demo-skl-150', process_id: PROC_RETURNS,  process_name: 'Returns Processing', proficiency_level: 1, certification_date: null, expiry_date: null, last_practiced_date: null },
    ],
    availability_overrides: [],
    preferences_json: {},
  },
]

// ── Convenient groupings ───────────────────────────────────────────────────────

export const demoEmployeesBySite = {
  [DEMO_SITE_AMS]: demoEmployees.filter((e) => e.home_site_id === DEMO_SITE_AMS),
  [DEMO_SITE_RTM]: demoEmployees.filter((e) => e.home_site_id === DEMO_SITE_RTM),
}
